name: build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * Mon' # every monday at 10:00.

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: windows-11
          #- name: server-2022
          #- name: server-2025
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Log the available disk space, so we can inspect it later.
      # NB GitHub-hosted runners have limited available disk space.
      #    see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
      - name: Show available disk space before build
        run: Get-PSDrive -PSProvider FileSystem

      # NB we are writing outside of the current working/job directory
      #    because it does not have sufficient available disk space.
      - name: Build
        run: pwsh uup-dump-get-windows-iso.ps1 ${{ matrix.name }} c:/output

      - name: Show available disk space after build
        run: Get-PSDrive -PSProvider FileSystem

      - name: Upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: c:/output/*.iso
      
      - name: Set artifact_url
        id: set_artifact_url
        run: echo "artifact_url=${{ steps.upload_artifact.outputs.artifact-url }}" >> $env:GITHUB_ENV
        
      - name: Build summary
        id: build_summary
        run: |
          $iso = Get-Content (Resolve-Path c:/output/*.json) | ConvertFrom-Json
          Add-Content $env:GITHUB_STEP_SUMMARY @"
          | Property | Value |
          | :--- | :--- |
          | Name | $($iso.name) |
          | Build | $($iso.build) |
          | Checksum | $($iso.checksum) |
          $($iso.images | ForEach-Object {"| Image Name | $($_.name) |"})
          | Iso | [$($iso.name)]($env:artifact_url) |
          | UUP dump | [$($iso.title)]($($iso.uupDump.downloadUrl)) |
          "@
          # Save the GITHUB_STEP_SUMMARY contents to a file
          (Get-Content $env:GITHUB_STEP_SUMMARY) | Set-Content summary.md
          echo "build=$($iso.build)" >> $env:GITHUB_ENV
          echo "name=$($iso.name)" >> $env:GITHUB_ENV
          echo "title=$($iso.title)" >> $env:GITHUB_ENV
          echo "iso_name=$($iso.name)" >> $env:GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.build }}.${{ github.run_number }}"
          release_name: ${{ env.name }}
          body_path: summary.md
          draft: false
          prerelease: false
